name: neilhester
favicon: null
layout_spectrum: 1
typography_spectrum: 0.24313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070103'
    - '#3f2b20'
    - '#b06852'
    - '#5a0006'
    - '#475b51'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
