name: neilhester
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#f6ba95'
    - '#6b2b10'
    - '#3d5b5d'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
