name: neilhester
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c4d4e3'
    - '#514b3d'
    - '#7e8887'
    - '#bf4619'
    - '#afad2e'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
